sudo: required
dist: trusty

language: haxe

# Add encrypted API key
env:
  global:
    - secure: OUD7gkCqQz0loMQIFFfKQaUPe23Ogp/huUOrXiZinekrrSOzyi5Su07EtgGRG8t4pSZqpp5BPsOQrXac9Tw7vY644H0tUQpWFzrFITZjmvaIyKhzFE9H0RORIIDHhGn/+f5bjpXNkiIeP80Bk8pwczS8fwKqJPkBfIjrTl/sQAqp5DS4Z0/gfkF0g08HlvjhuPfDITsg1agmp6RxWlEF8GHBdfR8XA7KTs3wzT60e957yKSqixg7dxh41udwL3hueHjbBM1ShWfgvb3pBJym3n7Qky3S6Dx+0Ne6MZDDKstZPZycbhbkKj2oo/kFDdrojCE9teiNcKpvgRDgLSA+w5ZbT1OT/kj/LDz5WLwxvtEXAD5Xea1rhhTCJKIfSBve5/E5JDzDxslPVawbOgnd2iLVxt+U3MJ4D7OP37kwsmfiureYs9CnZ5VhkYKoUxvmPMsQl/Je2BsSuH5v3qf29wLivcp06+/TBh810zIN1DYuipiWqI74ZBtRGYQyO422KvbUYdbpGQ00nEXNFnRvVsI7W8/Hm9CSbKMUG8rlxjg08hKUVuiA2ktVQ+8Co+Y1ZCvoE0A3sy4UjpfdR1OpJL0SYMflkw5n9/uxaN2+SYmb4zas4+ixdPo5TGYnmxGgHprgCe7HT56Th2fqea5wGDthnuA62bNMUxN11zQigQs=

os:
  - linux

# Blacklist
branches:
  only:
    - master

# Install dependencies
install:
  - haxelib install threejs

# Build the demo
script:
  - pushd src
  - haxe needs-ai.hxml
  - popd

# Deploy the generated demo using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: bin
  github_token: $GITHUB_API_KEY
  on:
    branch: master